# CosmoCanyon Configuration
# 
# Cosmo-Canyon is a personal computer
#

# Pathway to database directory
database_directory: "/esthar/diviner_data/database"

# Pathway to the tmp directory
tmp_directory: "/esthar/diviner_data/tmp"

# Pathway to useful tabs directory
useful_tabs_directory: "/esthar/diviner_data/txt_files/useful_tabs"

# Pathway to bad directory
bad_files_directory: "/esthar/diviner_data/txt_files/bad_files"

# Pathway to logs directory
log_directory: "/esthar/diviner_data/txt_files/logs"

# Max transaction size for SQL queries
transaction_size: 100000

# Max number of thread workers
max_workers: 32

# Pathway to AOI data directory
aoi_directory: "/esthar/diviner_data/data/aoi"

# Pathway to profiles directory
profiles_directory: "/test/profiles"